test:
	gcc -fopenmp -o test.o test.c

reduction:
	gcc -fopenmp -o pi-private-reduction.o pi-private-reduction.c

worksharing:
	gcc -fopenmp -o pi-worksharing.o pi-worksharing.c

parallel:
	gcc -fopenmp -o pi-parallel.o pi-parallel.c

critical:
	gcc -fopenmp -o pi-critical.o pi-critical.c
