#!/bin/bash

basedir=src/netflix

file=$basedir/create.titles.sql
#time hive -f $file

#file=$basedir/create.ratings100.sql
#file=$basedir/create.ratings100000.sql
#file=$basedir/create.ratings.sql
#file=$basedir/create.ratings50M.sql
file=$basedir/create.ratings10M.sql
#file=$basedir/create.ratings5M.sql
#time hive -f $file

file=$basedir/most_watched.sql
#time hive -f $file

file=$basedir/most_watched_periods.sql
#time hive -f $file

file=$basedir/most_popular_periods.sql
#time hive -f $file

#file=$basedir/most_popular_movies.sql
#file=$basedir/likeX_pairs.sql
#file=$basedir/most_similar_mid_pairs.sql
file=$basedir/most_similar_pairs.sql

time hive -f $file

#########################################
basedir=src/enron

file=$basedir/create.enron.sql
file=$basedir/most_received.sql
file=$basedir/most_sent.sql
file=$basedir/most_emails.sql
file=$basedir/most_correspondents.sql
file=$basedir/most_correspondent_pair.sql

# extract steve kean records
file=$basedir/steve.sql
#time hive -f $file

# extract steve kean unique emails
#time hive -e 'select sender, count(1) freq from enron_steve group by sender order by freq desc'

#time hive -e 'select subject from enron_steve'

file=$basedir/steve_words.sql
#time hive -f $file

file=$basedir/steve_recipients.sql
#time hive -f $file

# extract frequent word list (word count) from the subjects
file=$basedir/steve_subjects.sql
#time hive -f $file

##########################################
# extract ken lay records
file=$basedir/ken.sql
#time hive -f $file

# extract ken lay unique emails
#time hive -e 'select sender, count(1) freq from enron_ken group by sender order by freq desc'

#time hive -e 'select subject from enron_ken'

file=$basedir/ken_words.sql
#time hive -f $file

file=$basedir/ken_recipients.sql
#time hive -f $file

# extract frequent word list (word count) from the subjects
file=$basedir/ken_subjects.sql
#time hive -f $file

file=$basedir/outside_sent.sql
file=$basedir/outside_received.sql
file=$basedir/outside_enron.sql
#time hive -f $file
