#!/bin/bash

basedir=src/netflix

file=$basedir/create.titles.sql
#time hive -f $file

#file=$basedir/create.ratings100.sql
file=$basedir/create.ratings.sql
#time hive -f $file

file=$basedir/most_watched.sql
#time hive -f $file

file=$basedir/most_watched_periods.sql
#time hive -f $file

file=$basedir/most_popular_periods.sql
#time hive -f $file

file=$basedir/most_popular_movies.sql
#file=$basedir/likeX_pairs.sql
file=$basedir/most_similar_pairs.sql

time hive -f $file

basedir=src/enron

#########################################
# extract steve kean records
file=$basedir/steve.sql
#time hive -f $file

# extract steve kean unique emails
#time hive -e 'select sender, count(1) freq from enron_steve group by sender order by freq desc'

#time hive -e 'select subject from enron_steve'

file=$basedir/steve_words.sql
#time hive -f $file

file=$basedir/steve_recipients.sql
#time hive -f $file

# extract frequent word list (word count) from the subjects
file=$basedir/steve_subjects.sql
#time hive -f $file

##########################################
# extract ken lay records
file=$basedir/ken.sql
#time hive -f $file

# extract ken lay unique emails
#time hive -e 'select sender, count(1) freq from enron_ken group by sender order by freq desc'

#time hive -e 'select subject from enron_ken'

file=$basedir/ken_words.sql
#time hive -f $file

file=$basedir/ken_recipients.sql
#time hive -f $file

# extract frequent word list (word count) from the subjects
file=$basedir/ken_subjects.sql
#time hive -f $file

